title: Home
description: My Progress in Programming
author: Terence Lim
github: https://github.com/terryyylim
about: Currently, I'm a final-year undergraduate student from National University of Singapore (NUS) studying Business Analytics in the School of Computing, working on I-POMDPs for my Final Year Project. 
disqus_shortname: Blog Posts
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-medium
      link: "https://medium.com/@terencelimxp"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/terence-lim-365a39123/"
    - icon: fa-github
      link: "https://github.com/terryyylim"


urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://terryyylim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
